name: Auto build and publish Jekyll site to master branch

on:
  push:
    branches:
      - dev

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - name: Setup cache
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    # Setup Ruby and Bundler
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true

    # Build Jekyll site with production environment
    - name: Build Jekyll site
      run: |
        bundle install
        JEKYLL_ENV=production bundle exec jekyll build

    # Deploy to master branch
    - name: Deploy to master
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: master
        folder: _site
        token: ${{ secrets.GITHUB_TOKEN }}
        clean: true
